eureka:
  instance:
    hostname: cy-discovery
  client:
    service-url:
      defaultZone: http://cy-discovery:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0

security:
  jwt:
    key: BA9BD432115F6B82585C0300D83043BFF006F440