services:
  postgresql:
    container_name: cy-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin2024
      POSTGRES_PASSWORD: admin2024
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  zipkin:
    container_name: cy-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres: