services:

  user-service:
    container_name: cy-user
    image: compuya/user
    build:
      context: services/user
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - cy-network
    depends_on:
      - postgresql
    restart: unless-stopped

  postgresql:
    container_name: cy-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin2024
      POSTGRES_PASSWORD: admin2024
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - cy-network
    restart: unless-stopped

networks:
  cy-network:
    external: true

volumes:
  postgres: